server:
  port: 9000
spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://httpbin.org
          predicates:
            - Path=/anything/{segment}
        - id: strip_path_route
          uri: http://httpbin.org
          filters:
            - StripPrefix=1
          predicates:
            - Path=/httpbin/anything/{segment}
        - id: prefix_path_route
          uri: http://httpbin.org
          filters:
            - PrefixPath=/anything
          predicates:
            - Path=/{segment}


